### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'data/gaussian50-20-1-1.pt'

### ISSUE THREAD

**Issue by hmishfaq** [devzhk/LMCTS#1]
I am trying to run the experiment on synthetic data and it gives the error:
`FileNotFoundError: [Errno 2] No such file or directory: 'data/gaussian50-20-1-1.pt'`

How can I resolve it? Shouldn't it create this file/directory while training?

**Comment by devzhk** [comment]
Hey, thanks for your interest. I've added data setup section to the README. You can also download the data via this link https://hkzdata.s3.us-west-2.amazonaws.com/LMC-TS/gaussian50-20-1-1.pt.
