### ISSUE TITLE
Running sweeps

### ISSUE THREAD

**Issue by hmishfaq** [devzhk/LMCTS#2]
Could you please add how to run sweeps as well? That will be super helpful. I am running 
```
python3 run_simulation.py --config_path sweep/simulation/linear-linUCB.yaml --repeat 10 --log
```
but in W&B it only shows status of GPU usage. No regret plot. 
<img width="1292" alt="Screen Shot 2022-08-04 at 9 28 44 AM" src="https://user-images.githubusercontent.com/9067135/182902745-c7a6ac0c-03d4-4561-a3ee-522d55ea5a1f.png">

**Comment by devzhk** [comment]
Two quick fixes for this 
1. Set the default log value in the run_simulation.py to True. 
2. Or you can add --log to the command part of the configuration file.

**Comment by hmishfaq** [comment]
Sorry, I forgot to add --log in the original comment. The screenshot is what I get even after using --log flag.

**Comment by devzhk** [comment]
Can you try setting the default value to True in the run_simulation.py?

**Comment by hmishfaq** [comment]
I think the issue is `run_simulation.py` is not compatible with config files under `sweep` folder. After running the following 

```
python3 run_simulation.py --config_path sweep/simulation/linear-linUCB.yaml --repeat 1
```
I got the following error (I also printed the keys in the config which doesn't include `datapath`)
```
Random seed: 3272
#print(config.keys())
dict_keys(['program', 'method', 'metric', 'parameters', 'command', 'name', 'project', 'entity'])
Traceback (most recent call last):
  File "run_simulation.py", line 109, in <module>
    run(config, args)
  File "run_simulation.py", line 43, in run
    data = torch.load(config['datapath'])
KeyError: 'datapath'
````

Did you use different script other than `run_simulation.py` to do the hyper-param sweeping?

**Comment by hmishfaq** [comment]
I just double checked the `run_simulation.py` script and from my understanding it seems it doesn't have the code for looping through different hyperparameters [code link](https://github.com/devzhk/LMCTS/blob/master/run_simulation.py#L108)

In case you used some other script to run the sweeping, would you mind sharing it?

**Comment by devzhk** [comment]
Oh, I see. To run sweep, you need to run 
```bash
wandb sweep sweep/uci/shuttle-lmcts.yaml
wandb agent [agent id]
```
Check the wandb doc here https://docs.wandb.ai/guides/sweeps/quickstart.
